package greendao.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import greendao.bean.Travel;

import greendao.dao.TravelGreenDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig travelGreenDaoConfig;

    private final TravelGreenDao travelGreenDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        travelGreenDaoConfig = daoConfigMap.get(TravelGreenDao.class).clone();
        travelGreenDaoConfig.initIdentityScope(type);

        travelGreenDao = new TravelGreenDao(travelGreenDaoConfig, this);

        registerDao(Travel.class, travelGreenDao);
    }
    
    public void clear() {
        travelGreenDaoConfig.getIdentityScope().clear();
    }

    public TravelGreenDao getTravelGreenDao() {
        return travelGreenDao;
    }

}
