package greendao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import greendao.Travel;

import greendao.TravelDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig travelDaoConfig;

    private final TravelDao travelDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        travelDaoConfig = daoConfigMap.get(TravelDao.class).clone();
        travelDaoConfig.initIdentityScope(type);

        travelDao = new TravelDao(travelDaoConfig, this);

        registerDao(Travel.class, travelDao);
    }
    
    public void clear() {
        travelDaoConfig.getIdentityScope().clear();
    }

    public TravelDao getTravelDao() {
        return travelDao;
    }

}
